//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FareAlertSystem.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FareAlertSystem.Models.ModelResource", typeof(ModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code = {0}, Name = {1}.
        /// </summary>
        public static string CityDescriptionFormat {
            get {
                return ResourceManager.GetString("CityDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id = {0}, Journey = {1}.
        /// </summary>
        public static string FareAlertDescriptionFormat {
            get {
                return ResourceManager.GetString("FareAlertDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minumum = {0}, Maximum = {1}, Minimum Limit = {2}, Maximum Limit = {3}.
        /// </summary>
        public static string FareBoundDescriptionFormat {
            get {
                return ResourceManager.GetString("FareBoundDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airline = {0}, Fare= {1}, From = {2}, To = {3}.
        /// </summary>
        public static string FareSearchResultDescriptionFormat {
            get {
                return ResourceManager.GetString("FareSearchResultDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid age provided.
        /// </summary>
        public static string InvalidAge {
            get {
                return ResourceManager.GetString("InvalidAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid airline.
        /// </summary>
        public static string InvalidAirline {
            get {
                return ResourceManager.GetString("InvalidAirline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid city provided.
        /// </summary>
        public static string InvalidCity {
            get {
                return ResourceManager.GetString("InvalidCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid city code provided.
        /// </summary>
        public static string InvalidCityId {
            get {
                return ResourceManager.GetString("InvalidCityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid city name provided.
        /// </summary>
        public static string InvalidCityName {
            get {
                return ResourceManager.GetString("InvalidCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and Destination cannot be same.
        /// </summary>
        public static string InvalidCityPair {
            get {
                return ResourceManager.GetString("InvalidCityPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fare value is invalid.
        /// </summary>
        public static string InvalidFare {
            get {
                return ResourceManager.GetString("InvalidFare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid fare alert.
        /// </summary>
        public static string InvalidFareAlert {
            get {
                return ResourceManager.GetString("InvalidFareAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid frequency of fare alert.
        /// </summary>
        public static string InvalidFareAlertFrequency {
            get {
                return ResourceManager.GetString("InvalidFareAlertFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid fare constraint.
        /// </summary>
        public static string InvalidFareConstraint {
            get {
                return ResourceManager.GetString("InvalidFareConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid fare search result.
        /// </summary>
        public static string InvalidFareSearchResult {
            get {
                return ResourceManager.GetString("InvalidFareSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journey details are invalid.
        /// </summary>
        public static string InvalidJourneyDetails {
            get {
                return ResourceManager.GetString("InvalidJourneyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger details are invalid.
        /// </summary>
        public static string InvalidPassengerDetails {
            get {
                return ResourceManager.GetString("InvalidPassengerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: {0}, To: {1}, Onward: {2}, Return: {3}.
        /// </summary>
        public static string JourneyDescriptionFormat {
            get {
                return ResourceManager.GetString("JourneyDescriptionFormat", resourceCulture);
            }
        }
    }
}
